language: node_js
node_js:
  - "6"

before_install:
  - openssl aes-256-cbc -K $encrypted_e403eabacc39_key -iv $encrypted_e403eabacc39_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - chmod +x ./publi.sh

script:
  - rm -rf build/
  - npm install
  - npm run build
  - ./publi.sh


# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

sudo: false # route your build to the container-based infrastructure for a faster build
